package polygon

const base = "https://polygon.codeforces.com/api/"

const (
	problemsListEp                  = "problems.list"
	problemInfoEp                   = "problem.info"
	problemUpdateInfoEp             = "problem.updateInfo"
	problemStatementsEp             = "problem.statements"
	problemSaveStatementEp          = "problem.saveStatement"
	problemStatementResourcesEp     = "problem.statementResources"
	problemSaveStatementResourceEp  = "problem.saveStatementResource"
	problemCheckerEp                = "problem.checker"
	problemValidatorEp              = "problem.validator"
	problemInteractorEp             = "problem.interactor"
	problemFilesEp                  = "problem.files"
	problemSolutionsEp              = "problem.solutions"
	problemViewFileEp               = "problem.viewFile"
	problemViewSolutionEp           = "problem.viewSolution"
	problemScriptEp                 = "problem.script"
	problemTestsEp                  = "problem.tests"
	problemTestInputEp              = "problem.testInput"
	problemTestAnswerEp             = "problem.testAnswer"
	problemSetValidatorEp           = "problem.setValidator"
	problemSetCheckerEp             = "problem.setChecker"
	problemSetInteractorEp          = "problem.setInteractor"
	problemSaveFileEp               = "problem.saveFile"
	problemSaveSolutionEp           = "problem.saveSolution"
	problemEditSolutionExtraTagsEp  = "problem.editSolutionExtraTags"
	problemSaveScriptEp             = "problem.saveScript"
	problemSaveTestEp               = "problem.saveTest"
	problemSetTestGroupEp           = "problem.setTestGroup"
	problemEnableGroupsEp           = "problem.enableGroups"
	problemEnablePointsEp           = "problem.enablePoints"
	problemViewTestGroupEp          = "problem.viewTestGroup"
	problemSaveTestGroupEp          = "problem.saveTestGroup"
	problemViewTagsEp               = "problem.viewTags"
	problemSaveTagsEp               = "problem.saveTags"
	problemViewGeneralDescriptionEp = "problem.viewGeneralDescription"
	problemSaveGeneralDescriptionEp = "problem.saveGeneralDescription"
	problemViewGeneralTutorialEp    = "problem.viewGeneralTutorial"
	problemSaveGeneralTutorialEp    = "problem.saveGeneralTutorial"
	problemPackagesEp               = "problem.packages"
	problemPackageEp                = "problem.package"
	contestProblemsEp               = "contest.problems"
)
